//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hacksaar.SpaceControl.WP80.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hacksaar.SpaceControl.WP80.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear log.
        /// </summary>
        public static string AppBarButtonClearLogText {
            get {
                return ResourceManager.GetString("AppBarButtonClearLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarButtonSettingsText {
            get {
                return ResourceManager.GetString("AppBarButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Control.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Control.
        /// </summary>
        public static string AppTileTitle {
            get {
                return ResourceManager.GetString("AppTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Control.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log cleared..
        /// </summary>
        public static string Log_Logger_LogCleared {
            get {
                return ResourceManager.GetString("Log_Logger_LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished [Request public door state]..
        /// </summary>
        public static string Log_PublicDoorState_EndRequest {
            get {
                return ResourceManager.GetString("Log_PublicDoorState_EndRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Image-Url: {0}..
        /// </summary>
        public static string Log_PublicDoorState_ImageUrl {
            get {
                return ResourceManager.GetString("Log_PublicDoorState_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from {0}: {1}.
        /// </summary>
        public static string Log_PublicDoorState_SpaceApiResponse {
            get {
                return ResourceManager.GetString("Log_PublicDoorState_SpaceApiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting [Request public door state]....
        /// </summary>
        public static string Log_PublicDoorState_StartRequest {
            get {
                return ResourceManager.GetString("Log_PublicDoorState_StartRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public door state is &apos;{0}&apos;..
        /// </summary>
        public static string Log_PublicDoorState_State {
            get {
                return ResourceManager.GetString("Log_PublicDoorState_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished [Door-Buzz]..
        /// </summary>
        public static string Log_Sphinx_EndDoorBuzz {
            get {
                return ResourceManager.GetString("Log_Sphinx_EndDoorBuzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished [Door-Unlock]..
        /// </summary>
        public static string Log_Sphinx_EndDoorUnlock {
            get {
                return ResourceManager.GetString("Log_Sphinx_EndDoorUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting [Door-Buzz]....
        /// </summary>
        public static string Log_Sphinx_StartDoorBuzz {
            get {
                return ResourceManager.GetString("Log_Sphinx_StartDoorBuzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting [Door-Unlock]....
        /// </summary>
        public static string Log_Sphinx_StartDoorUnlock {
            get {
                return ResourceManager.GetString("Log_Sphinx_StartDoorUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}@{1}:{2}..
        /// </summary>
        public static string Log_TyShell_ConnectedSuccessfully {
            get {
                return ResourceManager.GetString("Log_TyShell_ConnectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected..
        /// </summary>
        public static string Log_TyShell_DisconnectedSuccessfully {
            get {
                return ResourceManager.GetString("Log_TyShell_DisconnectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        public static string Log_TyShell_Disconnecting {
            get {
                return ResourceManager.GetString("Log_TyShell_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from tyshell: {0}.
        /// </summary>
        public static string Log_TyShell_Response {
            get {
                return ResourceManager.GetString("Log_TyShell_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: {0}.
        /// </summary>
        public static string Log_TyShell_Result {
            get {
                return ResourceManager.GetString("Log_TyShell_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending command {0}.
        /// </summary>
        public static string Log_TyShell_SendingCommand {
            get {
                return ResourceManager.GetString("Log_TyShell_SendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to connect {0}@{1}:{2}.
        /// </summary>
        public static string Log_TyShell_TryingToConnect {
            get {
                return ResourceManager.GetString("Log_TyShell_TryingToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buzz.
        /// </summary>
        public static string MainPage_BtnBuzz {
            get {
                return ResourceManager.GetString("MainPage_BtnBuzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock.
        /// </summary>
        public static string MainPage_BtnUnlock {
            get {
                return ResourceManager.GetString("MainPage_BtnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Private Key File.
        /// </summary>
        public static string Settings_Caption_ConfirmPrivateKeyFileReplacement {
            get {
                return ResourceManager.GetString("Settings_Caption_ConfirmPrivateKeyFileReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP-Address.
        /// </summary>
        public static string Settings_Hostname {
            get {
                return ResourceManager.GetString("Settings_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Severity.
        /// </summary>
        public static string Settings_LogSeverity {
            get {
                return ResourceManager.GetString("Settings_LogSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to replace your Space Control private key file with {0}?.
        /// </summary>
        public static string Settings_Message_ConfirmPrivateKeyFileReplacement {
            get {
                return ResourceManager.GetString("Settings_Message_ConfirmPrivateKeyFileReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder is missing on your SD card, or it does not contain at least one .key file. Add a .key file and try again..
        /// </summary>
        public static string Settings_Message_MissingKeyFile {
            get {
                return ResourceManager.GetString("Settings_Message_MissingKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SD card is mssing. Insert an SD card that has a root folder containing at least one .key file and try again..
        /// </summary>
        public static string Settings_Message_MissingSdCard {
            get {
                return ResourceManager.GetString("Settings_Message_MissingSdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase (optional).
        /// </summary>
        public static string Settings_Passphrase {
            get {
                return ResourceManager.GetString("Settings_Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (optional).
        /// </summary>
        public static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key File.
        /// </summary>
        public static string Settings_PrivateKeyFile {
            get {
                return ResourceManager.GetString("Settings_PrivateKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space API Url.
        /// </summary>
        public static string Settings_SpaceApiUrl {
            get {
                return ResourceManager.GetString("Settings_SpaceApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH command timeout in seconds.
        /// </summary>
        public static string Settings_TimeoutInSeconds {
            get {
                return ResourceManager.GetString("Settings_TimeoutInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_Username {
            get {
                return ResourceManager.GetString("Settings_Username", resourceCulture);
            }
        }
    }
}
